language: scala

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.graphx-diameter-datasets

matrix:
  include:
    ## Tests on Scala 2.10.4
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="1.5.2"
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="1.6.3"
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: openjdk7
      scala: 2.10.6
      env: TEST_SPARK_VERSION="2.1.0"

    ## Tests on Scala 2.11.7
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.5.2"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="1.6.3"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: openjdk7
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.1.0"


script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
